site_name: LakePy
repo_url: https://github.com/ESIPFed/LakePy
site_description: Documentation for the LakePy Python Package
site_author: James Gearon & John Franey
google_analytics: ['UA-186311766-1', 'http://lakepydocs.com.s3-website.us-east-2.amazonaws.com/'] 
theme: 
    name: material
    logo: 'img/LPNu2.png'
    favicon: 'img/LPNu2.png'
    palette:
      primary: blue grey
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ESIPFed/LakePy/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@jake.gearon_34983
copyright: MIT
plugins:
    - search
    - mkdocstrings
markdown_extensions:
    - pymdownx.betterem:
        smart_enable: all
nav:
    - Home: index.md
    - API Reference: API.md
    - Contributing: contributing.md
    - License: LICENSE.md