site_name: LakePy
repo_url: https://github.com/ESIPFed/LakePy
site_description: Documentation for the LakePy Python Package
site_author: James Gearon & John Franey
google_analytics: ['UA-186311766-1', 'http://lakepydocs.com.s3-website.us-east-2.amazonaws.com/'] 
theme: 
    name: material
    custom_dir: custom_theme/
copyright: MIT
plugins:
    - search
    - mkdocstrings
nav:
    - Home: index.md
    - API Reference: API.md
    - Contributing: contributing.md
    - License: LICENSE.md